
<?php
$form = $this->form;
$form->prepare();
$form->setAttributes(array(
    'action' => $this->url.'/sacraments/marriages/addp',
    'method' => 'post',
    'name'   => 'myForm',
    'id'  => 'defaultForm'
));
?>
<div class="row">
    <div class="text-center">
        <h2 style="color:#178acc"><?php echo $this->title ?></h2>    
    </div>
</div>
<!-- /.row -->
<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading" style="color:#178acc">
                Registro de nuevo matrimonio
            </div>
            <div class="panel-body">
                <div class="row">
                    <?php echo $this->form()->openTag($form)?>
                    <div class="col-md-6">
                        <h3 style="color:#178acc">Informaci&oacute;n matrimonio</h3> 
                            <div class="form-group">
                                <label>* Libro:</label>
                                <?php $idBookofsacraments= $form->get('idBookofsacraments');
                                    echo $this->formSelect($idBookofsacraments);
                                    echo $this->formElementErrors($idBookofsacraments);
                                ?>
                            </div>
                            <div class="form-group">
                                <label>* P&aacute;gina:</label>
                                <?php $page= $form->get('page');
                                    echo $this->formSelect($page);
                                    echo $this->formElementErrors($page);
                                ?>
                            </div>
                            <div class="form-group">
                                <label>* Partida:</label>
                                <?php $item= $form->get('item');
                                    echo $this->formSelect($item);
                                    echo $this->formElementErrors($item);
                                ?>
                            </div>
                            <div class="form-group">
                                <label>* Fecha matrimonio:</label>
                                <?php $marriageDate= $form->get('marriageDate');
                                    echo $this->formInput($marriageDate);
                                    echo $this->formElementErrors($marriageDate);
                                ?> 
                            </div>                            
                            <div class="form-group">
                                <label>* P&aacute;rroco:</label>
                                <?php $marriagePriest= $form->get('marriagePriest');
                                    echo $this->formSelect($marriagePriest);
                                    echo $this->formElementErrors($marriagePriest);
                                ?>
                            </div>
                            <div class="form-group">
                                <?php $marriagePriestOthers= $form->get('marriagePriestOthers');
                                    echo $this->formInput($marriagePriestOthers);
                                    echo $this->formElementErrors($marriagePriestOthers);
                                ?>
                            </div>
                            <h3 style="color:#178acc">Informaci&oacute;n esposo</h3>
                            <div class="form-group">
                                <label>CI/Rua:</label>
                                <?php $ciMale= $form->get('ciMale');
                                    echo $this->formInput($ciMale);
                                    echo $this->formElementErrors($ciMale);
                                ?>
                            </div>
                            <div class="form-group">
                                <label>* Nombres:</label>
                                <?php $firstNameMale= $form->get('firstNameMale');
                                    echo $this->formInput($firstNameMale);
                                    echo $this->formElementErrors($firstNameMale);
                                ?>
                            </div>
                            <div class="form-group">
                                <label>Apellido paterno:</label>
                                <?php $firstSurnameMale= $form->get('firstSurnameMale');
                                    echo $this->formInput($firstSurnameMale);
                                    echo $this->formElementErrors($firstSurnameMale);
                                ?>
                            </div>
                            <div class="form-group">
                                <label>Apellido materno:</label>
                                <?php $secondSurnameMale= $form->get('secondSurnameMale');
                                    echo $this->formInput($secondSurnameMale);
                                    echo $this->formElementErrors($secondSurnameMale);
                                ?>
                            </div>
                            <div class="form-group">
                                <label>* Fecha nacimiento:</label>
                                <?php $birthDateMale= $form->get('birthDateMale');
                                    echo $this->formInput($birthDateMale);
                                    echo $this->formElementErrors($birthDateMale);
                                ?>
                            </div>
                            <div class="form-group">
                                <label>* Estado civil:</label>
                                <?php $maritalStatusMale= $form->get('maritalStatusMale');
                                    echo $this->formSelect($maritalStatusMale);
                                    echo $this->formElementErrors($maritalStatusMale);
                                ?>
                            </div>
                            <div class="form-group">
                                <label>* Parroquia bautismo:</label>
                                <?php $baptismParishMale= $form->get('baptismParishMale');
                                    echo $this->formSelect($baptismParishMale);
                                    echo $this->formElementErrors($baptismParishMale);
                                ?>
                            </div>
                            <div class="form-group">
                                <?php $baptismParishMaleOthers= $form->get('baptismParishMaleOthers');
                                    echo $this->formInput($baptismParishMaleOthers);
                                    echo $this->formElementErrors($baptismParishMaleOthers);
                                ?>
                            </div>
                            <div class="form-group">
                                <label>Nombres del padre:</label>
                                <?php $fatherNameMale= $form->get('fatherNameMale');
                                    echo $this->formInput($fatherNameMale);
                                ?>
                            </div>
                            <div class="form-group">
                                <label>Apellido paterno del padre:</label>
                                <?php $fatherFirstSurnameMale= $form->get('fatherFirstSurnameMale');
                                    echo $this->formInput($fatherFirstSurnameMale);
                                ?>
                            </div>
                            <div class="form-group">
                                <label>Apellido materno del padre:</label>
                                <?php $fatherSecondSurnameMale= $form->get('fatherSecondSurnameMale');
                                    echo $this->formInput($fatherSecondSurnameMale);
                                ?>
                            </div>
                            <div class="form-group">
                                <label>Nombre de la madre:</label>
                                <?php $matherNameMale= $form->get('matherNameMale');
                                    echo $this->formInput($matherNameMale);
                                ?>
                            </div>
                            <div class="form-group">
                                <label>Apellido paterno de la madre:</label>
                                <?php $matherFirstSurnameMale= $form->get('matherFirstSurnameMale');
                                    echo $this->formInput($matherFirstSurnameMale);
                                ?>
                            </div>
                            <div class="form-group">
                                <label>Apellido materno de la madre:</label>
                                <?php $matherSecondSurnameMale= $form->get('matherSecondSurnameMale');
                                    echo $this->formInput($matherSecondSurnameMale);
                                ?>
                            </div>
                            <h3 style="color:#178acc">Informaci&oacute;n esposa</h3>
                            <div class="form-group">
                                <label>CI/Rua:</label>
                                <?php $ciFemale= $form->get('ciFemale');
                                    echo $this->formInput($ciFemale);
                                    echo $this->formElementErrors($ciFemale);
                                ?>
                            </div>
                            <div class="form-group">
                                <label>* Nombres:</label>
                                <?php $firstNameFemale= $form->get('firstNameFemale');
                                    echo $this->formInput($firstNameFemale);
                                    echo $this->formElementErrors($firstNameFemale);
                                ?>
                            </div>
                            <div class="form-group">
                                <label>Apellido paterno:</label>
                                <?php $firstSurnameFemale= $form->get('firstSurnameFemale');
                                    echo $this->formInput($firstSurnameFemale);
                                    echo $this->formElementErrors($firstSurnameFemale);
                                ?>
                            </div>
                            <div class="form-group">
                                <label>Apellido materno:</label>
                                <?php $secondSurnameFemale= $form->get('secondSurnameFemale');
                                    echo $this->formInput($secondSurnameFemale);
                                    echo $this->formElementErrors($secondSurnameFemale);
                                ?>
                            </div> 
                            <div class="form-group">
                                <label>* Fecha nacimiento:</label>
                                <?php $birthDateFemale= $form->get('birthDateFemale');
                                    echo $this->formInput($birthDateFemale);
                                    echo $this->formElementErrors($birthDateFemale);
                                ?>
                            </div>
                            <div class="form-group">
                                <label>* Estado civil:</label>
                                <?php $maritalStatusFemale= $form->get('maritalStatusFemale');
                                    echo $this->formSelect($maritalStatusFemale);
                                    echo $this->formElementErrors($maritalStatusFemale);
                                ?>
                            </div>
                            <div class="form-group">
                                <label>* Parroquia bautismo:</label>
                                <?php $baptismParishFemale= $form->get('baptismParishFemale');
                                    echo $this->formSelect($baptismParishFemale);
                                    echo $this->formElementErrors($baptismParishFemale);
                                ?>
                            </div>
                            <div class="form-group">
                                <?php $baptismParishFemaleOthers= $form->get('baptismParishFemaleOthers');
                                    echo $this->formInput($baptismParishFemaleOthers);
                                    echo $this->formElementErrors($baptismParishFemaleOthers);
                                ?>
                            </div>
                            <div class="form-group">
                                <label>Nombres del padre:</label>
                                <?php $fatherNameFemale= $form->get('fatherNameFemale');
                                    echo $this->formInput($fatherNameFemale);
                                ?>
                            </div>
                            <div class="form-group">
                                <label>Apellido paterno del padre:</label>
                                <?php $fatherFirstSurnameFemale= $form->get('fatherFirstSurnameFemale');
                                    echo $this->formInput($fatherFirstSurnameFemale);
                                ?>
                            </div>
                            <div class="form-group">
                                <label>Apellido materno del padre:</label>
                                <?php $fatherSecondSurnameFemale= $form->get('fatherSecondSurnameFemale');
                                    echo $this->formInput($fatherSecondSurnameFemale);
                                ?>
                            </div>
                            <div class="form-group">
                                <label>Nombres de la madre:</label>
                                <?php $matherNameFemale= $form->get('matherNameFemale');
                                    echo $this->formInput($matherNameFemale);
                                ?>
                            </div> 
                            <div class="form-group">
                                <label>Apellido paterno de la madre:</label>
                                <?php $matherFirstSurnameFemale= $form->get('matherFirstSurnameFemale');
                                    echo $this->formInput($matherFirstSurnameFemale);
                                ?>
                            </div>
                            <div class="form-group">
                                <label>Apellido materno de la madre:</label>
                                <?php $matherSecondSurnameFemale= $form->get('matherSecondSurnameFemale');
                                    echo $this->formInput($matherSecondSurnameFemale);
                                ?>
                            </div> 
                    </div>
                    <!-- /.col-lg-6 (nested) -->
                    <div class="col-md-6">
                        <h3 style="color:#178acc">Informaci&oacute;n padrinos</h3>
                        <div class="form-group">
                            <label>* Nombres testigo de informaci&oacute;n 1:</label>
                            <?php
                            $godfatherNameOneInformation = $form->get('godfatherNameOneInformation');
                            echo $this->formInput($godfatherNameOneInformation);
                            ?>
                        </div>
                        <div class="form-group">
                            <label>* Apellidos testigo de informaci&oacute;n 1:</label>
                            <?php
                            $godfatherSurnameOneInformation = $form->get('godfatherSurnameOneInformation');
                            echo $this->formInput($godfatherSurnameOneInformation);
                            ?>
                        </div>
                        <div class="form-group">
                            <label>* Nombres testigo de informaci&oacute;n 2:</label>
                            <?php
                            $godfatherNameTwoInformation = $form->get('godfatherNameTwoInformation');
                            echo $this->formInput($godfatherNameTwoInformation);
                            ?>
                        </div>
                        <div class="form-group">
                            <label>* Apellidos testigo de informaci&oacute;n 2:</label>
                            <?php
                            $godfatherSurnameTwoInformation = $form->get('godfatherSurnameTwoInformation');
                            echo $this->formInput($godfatherSurnameTwoInformation);
                            ?>
                        </div>
                        <div class="form-group">
                            <label>* Nombres testigo presencial 1:</label>
                            <?php
                            $godfatherOneNamePresence = $form->get('godfatherNameOnePresence');
                            echo $this->formInput($godfatherOneNamePresence);
                            ?>
                        </div>
                        <div class="form-group">
                            <label>* Apellidos testigo presencial 1:</label>
                            <?php
                            $godfatherSurnameOnePresence = $form->get('godfatherSurnameOnePresence');
                            echo $this->formInput($godfatherSurnameOnePresence);
                            ?>
                        </div>
                        <div class="form-group">
                            <label>* Nombres testigo presencial 2:</label>
                            <?php
                            $godfatherNameTwoPresence= $form->get('godfatherNameTwoPresence');
                            echo $this->formInput($godfatherNameTwoPresence);
                            ?>
                        </div>  
                        <div class="form-group">
                            <label>* Apellidos testigo presencial 2:</label>
                            <?php
                            $godfatherSurnameTwoPresence= $form->get('godfatherSurnameTwoPresence');
                            echo $this->formInput($godfatherSurnameTwoPresence);
                            ?>
                        </div> 
                        <div class="form-group">
                            <label>* Doy fe p&aacute;rroco:</label>
                            <?php $attestPriest= $form->get('attestPriest');
                                echo $this->formSelect($attestPriest);
                                echo $this->formElementErrors($attestPriest);
                            ?>
                        </div>
                        <div class="form-group">
                            <?php $attestPriestOthers= $form->get('attestPriestOthers');
                                echo $this->formInput($attestPriestOthers);
                                echo $this->formElementErrors($attestPriestOthers);
                            ?>
                        </div>
                        <div class="form-group">
                            <label>Observaciones:</label>
                            <?php $observation= $form->get('observation');
                                echo $this->formTextArea($observation);
                                echo $this->formElementErrors($observation);
                            ?>
                        </div>
                        <div class="form-group">
                            <?php 
                                echo $this->messagesOne;
                                echo $this->messagesTwo;
                            ?>
                        </div>
                        <?php echo $this->formElement($form->get('register')) ?>
                        <a href="<?php echo $this->basePath() ?>/sacraments/marriages/indexp" class="btn btn-default" role="button">Cancelar</a>
                    </div>
                    <?php echo $this->form()->closeTag() ?>
                </div>
                <!-- /.row (nested) -->
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-12 -->
</div>
<!-- /.row -->
<script type="text/javascript">
$(document).ready(function() {
    $( "#inputMarriageDate" ).datepicker();
});
$(document).ready(function() {
    $( "#inputBirthDateMale" ).datepicker();
});

$(document).ready(function() {
    $( "#inputBirthDateFemale" ).datepicker();
}); 

$(document).ready(function () {
    $("#inputFirstSurnameMale").keyup(function () {
        var value = $(this).val();
        $("#inputFatherFirstSurnameMale").val(value);
    });
});

$(document).ready(function () {
    $("#inputSecondSurnameMale").keyup(function () {
        var value = $(this).val();
        $("#inputMatherFirstSurnameMale").val(value);
    });
});

$(document).ready(function () {
    $("#inputFirstSurnameFemale").keyup(function () {
        var value = $(this).val();
        $("#inputFatherFirstSurnameFemale").val(value);
    });
});

$(document).ready(function () {
    $("#inputSecondSurnameFemale").keyup(function () {
        var value = $(this).val();
        $("#inputMatherFirstSurnameFemale").val(value);
    });
});

$(document).ready(function () {
    $("#inputSelectMarriagePriest").change(function () {
        var value = $(this).val();
        if(value == 'Otros'){
            $("#inputMarriagePriestOthers").show();
        }else{
            $("#inputMarriagePriestOthers").hide();
        }    
    });
});

$(document).ready(function () {
    $("#inputSelectAttestPriest").change(function () {
        var value = $(this).val();
        if(value == 'Otros'){
            $("#inputAttestPriestOthers").show();
        }else{
            $("#inputAttestPriestOthers").hide();
        }    
    });
});

$(document).ready(function () {
    $("#inputBaptismParishMale").change(function () {
        var value = $(this).val();
        if(value == 'Otros'){
            $("#inputBaptismParishMaleOthers").show();
        }else{
            $("#inputBaptismParishMaleOthers").hide();
        }    
    });
});

$(document).ready(function () {
    $("#inputBaptismParishFemale").change(function () {
        var value = $(this).val();
        if(value == 'Otros'){
            $("#inputBaptismParishFemaleOthers").show();
        }else{
            $("#inputBaptismParishFemaleOthers").hide();
        }    
    });
});

$(document).ready(function() {
$('#inputSelectIdBook').change(function(){
    var idBook = $(this).val();
    $.ajax({
        type: "POST",
        url: "<?php echo $this->url.'/sacraments/marriages/getElementBookSacrament'; ?>",
        data: "idBook="+idBook,
        success: function(msg){
            $("#inputPage").html('<option value='+msg.split(",")[0]+'>'+msg.split(",")[0]+'</option>');
            $("#inputItem").html('<option value='+msg.split(",")[1]+'>'+msg.split(",")[1]+'</option>');
        }
    });
});
});

//$(document).ready(function() {    
//    //Al escribr dentro del input con id="service"
//    $('#ciMale').autocomplete(function(){
//        //Obtenemos el value del input
//        var service = $(this).val();        
//        var dataString = 'service='+service;
//        console.debug(dataString);
//        //Le pasamos el valor del input al ajax
//        $.ajax({
//            type: "POST",
//            url: "<?php echo $this->url.'/sacraments/marriages/getElementPersonAction'; ?>",
//            data: dataString,
//            success: function(data) {
//                //Escribimos las sugerencias que nos manda la consulta
////                $('#suggestions').fadeIn(1000).html(data);
////                //Al hacer click en algua de las sugerencias
////                $('.suggest-element').live('click', function(){
////                    //Obtenemos la id unica de la sugerencia pulsada
////                    var id = $(this).attr('id');
////                    //Editamos el valor del input con data de la sugerencia pulsada
////                    $('#service').val($('#'+id).attr('data'));
////                    //Hacemos desaparecer el resto de sugerencias
////                    $('#suggestions').fadeOut(1000);
////                });              
//            }
//        });
//    });              
//});    


 
$(document).ready(function() {
    $('#defaultForm').bootstrapValidator({
//        live: 'disabled',
        message: 'This value is not valid',
        feedbackIcons: {
            valid: 'glyphicon glyphicon-ok',
            invalid: 'glyphicon glyphicon-remove',
            validating: 'glyphicon glyphicon-refresh'
        },
        fields: {
            baptismPriest: {
                validators: {
                    notEmpty: {
                        message: 'El campo párroco es obligatorio.'
                    }
                }
            },
//            page: {
//                validators: {                    
//                    notEmpty: {
//                        message: 'El campo página es obligatorio.'
//                    },
//                    regexp: {
//                        regexp: /^[0-9]*$/,
//                        message: 'La página solo puede contener números enteros.'
//                    }
//                }
//            },
//            item: {
//                validators: {                    
//                    notEmpty: {
//                        message: 'El campo partida es obligatorio.'
//                    },
//                    regexp: {
//                        regexp: /^[0-9]*$/,
//                        message: 'La partida solo puede contener números enteros.'
//                    }
//                }
//            },            
//            idParishes: {
//                validators: {
//                    notEmpty: {
//                        message: 'El campo parroquia es obligatorio.'
//                    }
//                }
//            },
            idBookofsacraments: {
                validators: {
                    notEmpty: {
                        message: 'El campo libro es obligatorio.'
                    }
                }
            },
//            marriageDate: {
//                validators: {
//                    notEmpty: {
//                        message: 'La Fecha es requerido'
//                    }
//                }
//            },
            marriagePriest: {
                validators: {
                    notEmpty: {
                        message: 'El campo párroco es obligatorio.'
                    }
                }
            },
            firstNameMale: {
                validators: {
                    notEmpty: {
                        message: 'El campo nombre es obligatorio.'
                    }
                }
            },
//            lastNameMale: {
//                validators: {
//                    notEmpty: {
//                        message: 'El campo apellido es obligatorio.'
//                    }
//                }
//            },            
//            birthDateMale: {
//                validators: {
//                    notEmpty: {
//                        message: 'La fecha es requerido'
//                    }
//                }
//            },
            firstNameFemale: {
                validators: {
                    notEmpty: {
                        message: 'El campo nombre es obligatorio.'
                    }
                }
            },
//            lastNameFemale: {
//                validators: {
//                    notEmpty: {
//                        message: 'El campo apellido es obligatorio.'
//                    }
//                }
//            },            
//            birthDateFemale: {
//                validators: {
//                    notEmpty: {
//                        message: 'La fecha es requerido'
//                    }
//                }
//            },
            godfatherNameOneInformation: {
                validators: {
                    notEmpty: {
                        message: 'El campo nombres testigos de información es obligatorio.'
                    }
                }
            },
            godfatherSurnameOneInformation: {
                validators: {
                    notEmpty: {
                        message: 'El campo apellidos testigos de información es obligatorio.'
                    }
                }
            },
            godfatherNameTwoInformation: {
                validators: {
                    notEmpty: {
                        message: 'El campo nombres testigos de información es obligatorio.'
                    }
                }
            },
            godfatherSurnameTwoInformation: {
                validators: {
                    notEmpty: {
                        message: 'El campo apellidos testigos de información es obligatorio.'
                    }
                }
            },
            godfatherNameOnePresence: {
                validators: {
                    notEmpty: {
                        message: 'El campo nombres testigos presenciales es obligatorio.'
                    }
                }
            },
            godfatherSurnameOnePresence: {
                validators: {
                    notEmpty: {
                        message: 'El campo apellidos testigos presenciales es obligatorio.'
                    }
                }
            },
            godfatherNameTwoPresence: {
                validators: {
                    notEmpty: {
                        message: 'El campo nombres testigos presenciales es obligatorio.'
                    }
                }
            },
            godfatherSurnameTwoPresence: {
                validators: {
                    notEmpty: {
                        message: 'El campo apellidos testigos presenciales es obligatorio.'
                    }
                }
            },
            attestPriest: {
                validators: {
                    notEmpty: {
                        message: 'El campo párroco es obligatorio.'
                    }
                }
            }
        }
    });

    // Validate the form manually
    $('#validateBtn').click(function() {
        $('#defaultForm').bootstrapValidator('validate');
    });

    $('#resetBtn').click(function() {
        $('#defaultForm').data('bootstrapValidator').resetForm(true);
    });
});
</script>
