<?php
$form = $this->form;
$form->setAttributes(array(
    'action' => $this->url.'/users/certificate/load/'.$this->data->id,
    'method' => 'post',
    'name'   => 'myForm',
    'id'  => 'defaultForm'
));
$form->prepare();
?>
<div class="row">
    <div class="text-center">
        <h2 style="color:#178acc"><?php echo $this->title ?></h2>    
    </div>
</div>
<!-- /.row -->
<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading" style="color:#178acc">
                Registro de cargar certificado
            </div>
            <div class="panel-body">
                <div class="row">                    
                    <div class="col-md-6">
                        <h3 style="color:#178acc">Informaci&oacute;n b&aacute;sica</h3>
                        <p>Usuario: <strong><?php echo $this->data->charge." ".$this->data->firstName." ".$this->data->lastName?></strong></p>                        
                        <?php echo $this->form()->openTag($form)?>    
                            <div class="form-group">
                                <label for="fileupload">* CertificadoCrt.crt:</label>
                                <?php $fileupload= $form->get('cert-file');
                                    echo $this->formInput($fileupload);
                                    echo $this->formElementErrors($fileupload);
                                ?>
                            </div>
                            <div class="form-group">
                                <label for="fileupload2">* CertificadoKey.key:</label>
                                <?php $fileKey= $form->get('key-file');
                                    echo $this->formInput($fileKey);
                                    echo $this->formElementErrors($fileKey);
                                    echo $this->messages;
                                ?>
                            </div>
                            <?php echo $this->formElement($form->get('load')) ?>
                            <a href="<?php echo $this->basePath() ?>/users/user/index" class="btn btn-default" role="button">Cancelar</a>
                        <?php echo $this->form()->closeTag() ?>
                    </div>
                    <!-- /.col-lg-6 (nested) -->
                    
                </div>
                <!-- /.row (nested) -->
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-12 -->
</div>
<!-- /.row -->
<script type="text/javascript">


//$(document).ready(function() {
//    $('#defaultForm').bootstrapValidator({
////        live: 'disabled',
//        message: 'This value is not valid',
//        feedbackIcons: {
//            valid: 'glyphicon glyphicon-ok',
//            invalid: 'glyphicon glyphicon-remove',
//            validating: 'glyphicon glyphicon-refresh'
//        },
//        fields: {            
//            
//        }
//    });
//
//    // Validate the form manually
//    $('#validateBtn').click(function() {
//        $('#defaultForm').bootstrapValidator('validate');
//    });
//
//    $('#resetBtn').click(function() {
//        $('#defaultForm').data('bootstrapValidator').resetForm(true);
//    });
//});
</script>