<?php
$form = $this->form;
$form->prepare();
$form->setAttributes(array(
    'action' => $this->url.'/sacraments/confirmations/edit/'.$this->id,
    'method' => 'post',
    'name'   => 'myForm',
    'id'  => 'defaultForm'
));
?>
<div class="row">
    <div class="text-center">
        <h2 style="color:#178acc"><?php echo $this->title ?></h2>    
    </div>
</div>

<!-- /.row -->
<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading" style="color:#178acc">
                Registro de editar confirmaci&oacute;n
            </div>
            <div class="panel-body">
                <div class="row">
                    <?php echo $this->form()->openTag($form)?>
                    <div class="col-md-6">
                        <h3 style="color:#178acc">Informaci&oacute;n confirmaci&oacute;n</h3> 
                            <?php $id= $form->get('id');
                                echo $this->formInput($id);
                            ?>                           
                            <div class="form-group">
                                <label>* Parroquia:</label>
                                <?php $idParishes= $form->get('idParishes');
                                    echo $this->formSelect($idParishes);
                                    echo $this->formElementErrors($idParishes);
                                ?>
                            </div>
                            <div class="form-group">
                                <label>* Libro:</label>
                                <?php $idBookofsacraments= $form->get('idBookofsacraments');
                                    echo $this->formSelect($idBookofsacraments);
                                    echo $this->formElementErrors($idBookofsacraments);
//                                    echo $this->messages;
                                ?>
                            </div>
                            <div class="form-group">
                                <label>* P&aacute;gina:</label>
                                <?php $page= $form->get('page');
                                    echo $this->formSelect($page);
                                    echo $this->formElementErrors($page);
                                ?>
                            </div>
                            <div class="form-group">
                                <label>* Partida:</label>
                                <?php $item= $form->get('item');
                                    echo $this->formSelect($item);
                                    echo $this->formElementErrors($item);
                                ?>
                            </div>
                            <p><strong>* Fecha confirmaci&oacute;n:</strong></p>
                            <div class="form-group input-group">
                                <!--<label>* Fecha confirmaci&oacute;n:</label>-->
                                <?php $confirmationDate= $form->get('confirmationDate');
                                    echo $this->formInput($confirmationDate);
                                    echo $this->formElementErrors($confirmationDate);
                                ?> 
                                <span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span>
                            </div>
                            <div class="form-group">
                            <label>* Obispo o Confirmante:</label>                            
                            <?php $attestPriest= $form->get('attestPriest');
                                echo $this->formSelect($attestPriest);
                                echo $this->formElementErrors($attestPriest);
                            ?>
                            </div>
                            <div class="form-group">
                                <?php $attestPriestOthers= $form->get('attestPriestOthers');
                                    echo $this->formInput($attestPriestOthers);
                                    echo $this->formElementErrors($attestPriestOthers);
                                ?>
                            </div>
                            <h3 style="color:#178acc">Informaci&oacute;n persona</h3>
                            <div class="form-group">
                                <label>CI/Rua:</label>
                                <?php $ci= $form->get('ci');
                                    echo $this->formInput($ci);
                                    echo $this->formElementErrors($ci);
                                ?>
                            </div>
                            <div class="form-group">
                                <label>* Nombres:</label>
                                <?php $firstName= $form->get('firstName');
                                    echo $this->formInput($firstName);
                                    echo $this->formElementErrors($firstName);
                                ?>
                            </div>
                            <div class="form-group">
                                <label>Apellido paterno:</label>
                                <?php $firstSurname= $form->get('firstSurname');
                                    echo $this->formInput($firstSurname);
                                    echo $this->formElementErrors($firstSurname);
                                ?>
                            </div>
                            <div class="form-group">
                                <label>Apellido materno:</label>
                                <?php $secondSurname= $form->get('secondSurname');
                                    echo $this->formInput($secondSurname);
                                    echo $this->formElementErrors($secondSurname);
                                ?>
                            </div>
                            <p><strong>* Fecha nacimiento:</strong></p>
                            <div class="form-group input-group">
                                <!--<label>* Fecha nacimiento:</label>-->
                                <?php $birthDate= $form->get('birthDate');
                                    echo $this->formInput($birthDate);
                                    echo $this->formElementErrors($birthDate);
                                ?>
                                <span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span>
                            </div>
                            <div class="form-group">
                                <label>* Parroquia bautismo:</label>
                                <?php $baptismParish= $form->get('baptismParish');
                                    echo $this->formSelect($baptismParish);
                                    echo $this->formElementErrors($baptismParish);
                                ?>
                            </div>
                            <div class="form-group">
                                <?php $baptismParishOthers= $form->get('baptismParishOthers');
                                    echo $this->formInput($baptismParishOthers);
                                    echo $this->formElementErrors($baptismParishOthers);
                                ?>
                            </div>
                            <div class="form-group">
                                <label>Nombres del padre:</label>
                                <?php $fatherName= $form->get('fatherName');
                                    echo $this->formInput($fatherName);
                                ?>
                            </div>
                            <div class="form-group">
                                <label>Apellido paterno del padre:</label>
                                <?php $fatherFirstSurname= $form->get('fatherFirstSurname');
                                    echo $this->formInput($fatherFirstSurname);
                                ?>
                            </div>
                            <div class="form-group">
                                <label>Apellido materno del padre:</label>
                                <?php $fatherSecondSurname= $form->get('fatherSecondSurname');
                                    echo $this->formInput($fatherSecondSurname);
                                ?>
                            </div>
                            <div class="form-group">
                                <label>Nombres de la madre:</label>
                                <?php $matherName= $form->get('matherName');
                                    echo $this->formInput($matherName);
                                ?>
                            </div>
                            <div class="form-group">
                                <label>Apellido paterno de la madre:</label>
                                <?php $matherFirstSurname= $form->get('matherFirstSurname');
                                    echo $this->formInput($matherFirstSurname);
                                ?>
                            </div> 
                            <div class="form-group">
                                <label>Apellidos materno de la madre:</label>
                                <?php $matherSecondSurname= $form->get('matherSecondSurname');
                                    echo $this->formInput($matherSecondSurname);
                                ?>
                            </div>                        
                    </div>
                    <!-- /.col-lg-6 (nested) -->
                    <div class="col-md-6">
                        <h3 style="color:#178acc">Informaci&oacute;n padrinos</h3>                            
                            <div class="form-group">
                                <label>* Nombres del padrino(a) 1:</label>
                                <?php $godfatherNameOne= $form->get('godfatherNameOne');
                                    echo $this->formInput($godfatherNameOne);
                                ?>
                            </div>
                            <div class="form-group">
                                <label>* Apellidos del padrino(a) 1:</label>
                                <?php $godfatherSurnameOne= $form->get('godfatherSurnameOne');
                                    echo $this->formInput($godfatherSurnameOne);
                                ?>
                            </div>
                            <div class="form-group">
                                <label>Nombres del padrino(a) 2:</label>
                                <?php $godfatherNameTwo= $form->get('godfatherNameTwo');
                                    echo $this->formInput($godfatherNameTwo);
                                ?>
                            </div>
                            <div class="form-group">
                                <label>Apellidos del padrino(a) 2:</label>
                                <?php $godfatherSurnameTwo= $form->get('godfatherSurnameTwo');
                                    echo $this->formInput($godfatherSurnameTwo);
                                ?>
                            </div>
                            <div class="form-group">
                            <label>Observaciones:</label>
                            <?php $observation= $form->get('observation');
                                echo $this->formTextArea($observation);
                                echo $this->formElementErrors($observation);
                            ?>
                        </div>
                        <div class="form-group">
                            <?php 
                                echo $this->messages;
                            ?>
                        </div>                        
                        <?php echo $this->formElement($form->get('modify')) ?>
                        <a href="<?php echo $this->basePath() ?>/sacraments/confirmations/index" class="btn btn-default" role="button">Cancelar</a>
                                            
                    </div>
                    <?php echo $this->form()->closeTag() ?>
                </div>
                <!-- /.row (nested) -->
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-12 -->
</div>
<!-- /.row -->
<script type="text/javascript">
$(document).ready(function() {
    var nowTemp = new Date();
    var now = new Date(nowTemp.getFullYear(), nowTemp.getMonth(), nowTemp.getDate(), 0, 0, 0, 0);

    $('#inputConfirmationDate').datepicker({
      onRender: function(date) {
        return date.valueOf() > now.valueOf() ? 'disabled' : '';
      }
    });
});
$(document).ready(function() {
    var nowTemp = new Date();
    var now = new Date(nowTemp.getFullYear(), nowTemp.getMonth(), nowTemp.getDate(), 0, 0, 0, 0);

    $('#inputBirthDate').datepicker({
      onRender: function(date) {
        return date.valueOf() > now.valueOf() ? 'disabled' : '';
      }
    });
});  
$(document).ready(function() {

$('#inputSelectIdParish').change(function(){
    var idParish = $(this).val();
    $.ajax({
        type: "POST",
        url: "<?php echo $this->url.'/sacraments/baptisms/getBookSacrament'; ?>",
        data: "idParish="+idParish,
        success: function(msg){ 
            $("#inputSelectIdBook").html(msg);
        }
    });
});
});    
 
$(document).ready(function() {
    $('#defaultForm').bootstrapValidator({
//        live: 'disabled',
        message: 'This value is not valid',
        feedbackIcons: {
            valid: 'glyphicon glyphicon-ok',
            invalid: 'glyphicon glyphicon-remove',
            validating: 'glyphicon glyphicon-refresh'
        },
        fields: {
            baptismPriest: {
                validators: {
                    notEmpty: {
                        message: 'El Parroco es requerido'
                    }
                }
            },
            page: {
                validators: {                    
                    notEmpty: {
                        message: 'La Pagina es requerido'
                    },
                    regexp: {
                        regexp: /^[0-9]*$/,
                        message: 'La Pagina solo puede contener numeros'
                    }
                }
            },
            item: {
                validators: {                    
                    notEmpty: {
                        message: 'El Item es requerido'
                    },
                    regexp: {
                        regexp: /^[0-9]*$/,
                        message: 'El Item solo puede contener numeros'
                    }
                }
            },
            firstName: {
                validators: {
                    notEmpty: {
                        message: 'El Nombre es requerido'
                    }
                }
            },
            lastName: {
                validators: {
                    notEmpty: {
                        message: 'El Apellido es requerido'
                    }
                }
            },
//            confirmationDate: {
//                validators: {
//                    notEmpty: {
//                        message: 'El campo fecha de confirmación es obligatorio.'
//                    },
//                    date: {
//                        format: 'YYYY-MM-DD',
//                        message: 'El formato de la fecha es incorrecto.'
//                    }
//                }
//            },
//            birthDate: {
//                validators: {
//                    notEmpty: {
//                        message: 'El campo fecha de nacimiento es obligatorio.'
//                    },
//                    date: {
//                        format: 'YYYY-MM-DD',
//                        message: 'El formato de la fecha es incorrecto.'
//                    }
//                }
//            },
            attestPriest: {
                validators: {
                    notEmpty: {
                        message: 'El Parroco es requerido'
                    }
                }
            }
        }
    });

    // Validate the form manually
    $('#validateBtn').click(function() {
        $('#defaultForm').bootstrapValidator('validate');
    });

    $('#resetBtn').click(function() {
        $('#defaultForm').data('bootstrapValidator').resetForm(true);
    });
});
</script>

