<div class="row">
    <div class="text-center">
        <h2 style="color:#178acc"><?php echo $this->title ?></h2>    
    </div>
</div>
<!-- /.row -->
<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading" style="color:#178acc">
                Personas
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                <div class="table-responsive">
                    <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                        <thead>
                            <tr>
                                <th>CI/Rua</th>  
                                <th>Persona</th>                                                               
                                <th>Fecha nacimiento</th>
                                <th>Parroquia</th>
                                <th>Acciones</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php foreach($this->data as $data_item){ ?>                           
                            <tr class="gradeC">                
                                <td><?php echo  $data_item->ci?></td>
                                <td><?php echo  $data_item->firstName." ".$data_item->firstSurname." ".$data_item->secondSurname?></td>                                
                                <td><?php echo  $data_item->birthDate ?></td>
                                <?php if(!empty($data_item->parishNameBaptism)){?>
                                <td><?php echo  $data_item->parishNameBaptism ?></td>
                                <?php }if(!empty($data_item->parishNameConfirmation)){?>
                                <td><?php echo  $data_item->parishNameConfirmation ?></td>
                                <?php }if(!empty($data_item->parishNameMarriage)){?>
                                <td><?php echo  $data_item->parishNameMarriage ?></td>
                                <?php } ?>
                                <td>
                                <a href="<?php echo $this->basePath() ?>/sacraments/person/view/<?php echo  $data_item->id?>" title="Ver" style="color:#178acc"><span class="glyphicon glyphicon-eye-open"></span></a>
                                </td>
                            </tr>
                            <?php } ?>
                        </tbody>
                    </table>
                </div>
                <!-- /.table-responsive -->                
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-12 -->
</div>