<div class="row">
    <div class="text-center">
        <h2 style="color:#178acc"><?php echo $this->title ?></h2>    
    </div>
</div>
<!-- /.row -->
<?php setlocale(LC_TIME, "spanish"); ?>
<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <a href="<?php echo $this->basePath() ?>/sacraments/person/indexp" style="color:#178acc"><span class="glyphicon glyphicon-circle-arrow-left"></span> Atr&aacute;s</a>
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body"> 
<!--                <div class="col-lg-2">
                    <img data-src="holder.js/140x140" class="img-rounded" alt="140x140" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxNDAiIGhlaWdodD0iMTQwIj48cmVjdCB3aWR0aD0iMTQwIiBoZWlnaHQ9IjE0MCIgZmlsbD0iI2VlZSI+PC9yZWN0Pjx0ZXh0IHRleHQtYW5jaG9yPSJtaWRkbGUiIHg9IjcwIiB5PSI3MCIgc3R5bGU9ImZpbGw6I2FhYTtmb250LXdlaWdodDpib2xkO2ZvbnQtc2l6ZToxMnB4O2ZvbnQtZmFtaWx5OkFyaWFsLEhlbHZldGljYSxzYW5zLXNlcmlmO2RvbWluYW50LWJhc2VsaW5lOmNlbnRyYWwiPjE0MHgxNDA8L3RleHQ+PC9zdmc+" style="width: 140px; height: 140px;">                
                </div>-->
                <div class="col-md-8">
                    <h3 style="color:#178acc">Informaci&oacute;n de la persona</h3>
                    <p>CI/Rua: <strong><?php echo (empty($this->data->ci))? '' : $this->data->ci;?></strong></p>
                    <p>Nombre: <strong><?php echo $this->data->firstName." ".$this->data->firstSurname." ".$this->data->secondSurname ?></strong></p>
                    <p>Fecha de nacimiento: <strong><?php echo strftime("%d de %B del %Y",strtotime($this->data->birthDate)) ?></strong></p>
                    <p>Nacido en: <strong><?php echo ($this->data->bornIn == 'Otros'  || empty($this->data->bornIn)) ? $this->data->bornInOthers : $this->data->bornIn."-".$this->data->bornInProvince ?></strong></p>
                    <p>Padre: <strong><?php echo $this->data->fatherName ?></strong></p>
                    <p>Madre: <strong><?php echo $this->data->matherName ?></strong></p> 
                    <?php if(!empty($this->data->parishNameBaptism)){?>
                    <p>Parroquia donde realizó el sacramento: <strong><?php echo $this->data->parishNameBaptism ?></strong></p> 
                    <?php }if(!empty($this->data->parishNameConfirmation)){?>
                    <p>Parroquia donde realizó el sacramento: <strong><?php echo $this->data->parishNameConfirmation ?></strong></p> 
                    <?php }if(!empty($this->data->parishNameMarriage)){?>
                    <p>Parroquia donde realizó el sacramento: <strong><?php echo $this->data->parishNameMarriage ?></strong></p> 
                    <?php } ?>
                    <?php if(empty($this->data->idBaptism)){ ?>
                    <p>Bautizado(a): <strong><?php echo "No"?></strong></p>
                    <?php }else{ ?>
                    <p>Bautizado(a): <strong><?php echo "Si"?></strong></p> 
                    <!--<a href="<?php echo $this->basePath() ?>/sacraments/baptisms/viewp/<?php echo $this->data->idBaptism ?>" style="color:#178acc"> Ver detalles</a></strong></p>-->
                    <?php } ?>
                    <?php if(empty($this->data->idConfirmation)){ ?>
                    <p>Confirmado(a): <strong><?php echo "No" ?></strong></p>
                    <?php }else{ ?>
                    <p>Confirmado(a): <strong><?php echo "Si" ?></strong></p> 
                    <!--<a href="<?php echo $this->basePath() ?>/sacraments/confirmations/viewp/<?php echo $this->data->idConfirmation ?>" style="color:#178acc"> Ver detalles</a></strong></p>-->
                    <?php } ?>
                    <?php if(empty($this->data->idMarriage)){ ?>
                    <p>Casado(a): <strong><?php echo "No" ?></strong></p>
                    <?php }else{ ?>
                    <p>Casado(a): <strong><?php echo "Si" ?></strong></p> 
                    <!--<a href="<?php echo $this->basePath() ?>/sacraments/marriages/viewp/<?php echo $this->data->idMarriage ?>" style="color:#178acc"> Ver detalles</a></strong></p>-->
                    <?php } ?>
                    </br>                    
                </div>
                </div>            
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-12 -->
</div>
