<?php
//============================================================+
// File name   : example_002.php
// Begin       : 2008-03-04
// Last Update : 2013-05-14
//
// Description : Example 002 for TCPDF class
//               Removing Header and Footer
//
// Author: Nicola Asuni
//
// (c) Copyright:
//               Nicola Asuni
//               Tecnick.com LTD
//               www.tecnick.com
//               info@tecnick.com
//============================================================+

/**
 * Creates an example PDF TEST document using TCPDF
 * @package com.tecnick.tcpdf
 * @abstract TCPDF - Example: Removing Header and Footer
 * @author Nicola Asuni
 * @since 2008-03-04
 */

// Include the main TCPDF library (search for installation path).
//require_once('tcpdf_include.php');

// Extend the TCPDF class to create custom Header and Footer
//setlocale(LC_ALL,"es_ES");
if(!empty($this->data->certificateName)){

class MYPDF extends TCPDF {

    //Page header
//    public function Header() {
//        // Logo
//        $image_file = K_PATH_IMAGES.'logo_example.jpg';
//        $this->Image($image_file, 10, 10, 15, '', 'JPG', '', 'T', false, 300, '', false, false, 0, false, false, false);
//        // Set font
//        $this->SetFont('helvetica', 'B', 20);
//        // Title
//        $this->Cell(0, 15, '<< TCPDF Example 003 >>', 0, false, 'C', 0, '', 0, false, 'M', 'M');
//    }

    // Page footer
    public function Footer() {        
        // Page 
        $this->Cell(0, 10, 'Puedes comprobar la autencidad de este documento en www.arzobispado-cochabamba.com', 0, false, 'L', 0, '', 0, false, 'T', 'M');
    }
}
// create new PDF document
$pdf = new MYPDF(PDF_PAGE_ORIENTATION, PDF_UNIT, PDF_PAGE_FORMAT, true, 'UTF-8', false);

// set document information
$pdf->SetCreator(PDF_CREATOR);
$pdf->SetAuthor('Victor Peña');
$pdf->SetTitle('TCPDF Certificado de bautismo');
$pdf->SetSubject('TCPDF bautismo');
$pdf->SetKeywords('TCPDF, PDF, example, test, guide');

// set default header data
//$pdf->SetHeaderData(PDF_HEADER_LOGO, PDF_HEADER_LOGO_WIDTH, PDF_HEADER_TITLE, PDF_HEADER_STRING);

// remove default header/footer
$pdf->setPrintHeader(false);
$pdf->setPrintFooter(true);

// set header and footer fonts
$pdf->setHeaderFont(Array(PDF_FONT_NAME_MAIN, '', PDF_FONT_SIZE_MAIN));
$pdf->setFooterFont(Array(PDF_FONT_NAME_DATA, '', PDF_FONT_SIZE_DATA));

// set default monospaced font
$pdf->SetDefaultMonospacedFont(PDF_FONT_MONOSPACED);

// set margins
$pdf->SetMargins(PDF_MARGIN_LEFT, PDF_MARGIN_TOP, PDF_MARGIN_RIGHT);
$pdf->SetHeaderMargin(PDF_MARGIN_HEADER);
$pdf->SetFooterMargin(PDF_MARGIN_FOOTER);

// set auto page breaks
$pdf->SetAutoPageBreak(TRUE, PDF_MARGIN_BOTTOM);

// set image scale factor
$pdf->setImageScale(PDF_IMAGE_SCALE_RATIO);

// set some language-dependent strings (optional)
if (@file_exists(dirname(__FILE__).'/lang/eng.php')) {
    require_once(dirname(__FILE__).'/lang/eng.php');
    $pdf->setLanguageArray($l);
}

$day = strftime("%A",strtotime($this->data->baptismDate));
if($day == "Monday")
    $day= "Lunes";
if($day == "Tuesday")
    $day= "Martes";
if($day == "Wednesday")
    $day= "Miércoles";
if($day == "Thursday")
    $day= "Jueves";
if($day == "Friday")
    $day= "Viernes";
if($day == "Saturday")
    $day= "Sábado";
if($day == "Sunday")
    $day= "Domingo";
//setlocale(LC_ALL,"es_ES");
setlocale(LC_TIME, "spanish");


if($this->data->bornIn == 'Otros')
    $bornInPrint = $this->data->bornInOthers;
else
    $bornInPrint = $this->data->bornIn."-".$this->data->bornInProvince; 

if($this->data->baptismPriest == 'Otros')
    $baptismPriestPrint = $this->data->baptismPriestOthers;
else
    $baptismPriestPrint = $this->data->baptismPriest;

if($this->data->attestPriest == 'Otros')
    $attestPriestPrint = $this->data->attestPriestOthers;
else
    $attestPriestPrint = $this->data->attestPriest;

$godfathersPrint= '';
if(!empty($this->data->godfatherNameTwo))
    $godfathersPrint = $this->data->godfatherNameOne." ".$this->data->godfatherSurnameOne."</strong> y <strong>".$this->data->godfatherNameTwo." ".$this->data->godfatherSurnameTwo;
else
    $godfathersPrint = $this->data->godfatherNameOne." ".$this->data->godfatherSurnameOne;

$parentPrint = '';
if(!empty($this->data->fatherName)){
    if(!empty($this->data->matherName)){
        $parentPrint = $this->data->fatherName." ".$this->data->fatherFirstSurname." ".$this->data->fatherSecondSurname."</strong> y de: <strong>".$this->data->matherName." ".$this->data->matherFirstSurname." ".$this->data->matherSecondSurname;
    }else{
        $parentPrint = $this->data->fatherName." ".$this->data->fatherFirstSurname." ".$this->data->fatherSecondSurname;
    }
}else{
    $parentPrint = $this->data->matherName." ".$this->data->matherFirstSurname." ".$this->data->matherSecondSurname;
}

// ---------------------------------------------------------
//if($this->data->idUserCertificate != '0'){
// set certificate file
//$certificate = 'file://'.$this->url.'/cert/tcpdf.crt'; 
//$public_key  = 'file://'.$this->url.'/cert/tcpdf.crt';
$certificate = 'file://C:/xampp/htdocs/system_AC/public/certificates/cert/'.$this->data->certificateName; 
$private_key = 'file://C:/xampp/htdocs/system_AC/public/certificates/key/'.$this->data->privateKey;  
//$certificate  = 'file://C:/xampp/htdocs/SISTEMA_SISSR/vendor/tecnick.com/tcpdf/examples/data/cert/tcpdf.crt'; 
//$public_key  = 'file://C:/xampp/htdocs/SISTEMA_SISSR/vendor/tecnick.com/tcpdf/examples/data/cert/tcpdf.crt'; 
$info = array(
    'Name' => 'TCPDF',
    'Location' => 'COCHABAMBA - BOLIVIA',
    'Reason' => 'Certificate PKI', 
    'ContactInfo' => 'http://www.arzobispado-cochabamba.com');
$pdf->setSignature($certificate, $private_key, '', '', 2, $info);
//$pdf->setSignatureAppearance($x=53, $y=133, $w=65, $h=62); 
//}

// ---------------------------------------------------------

// set font
$pdf->SetFont('times', 'B', 23);
// add a page
$pdf->AddPage();
// set some text to print
$txt = <<<EOD
        
        
CERTIFICADO DE BAUTISMO
EOD;
// print a block of text using Write()
$pdf->Write(0, $txt, '', 0, 'C', true, 0, false, false, 0);
$pdf->SetFont('times', '', 14);
$txt1 = <<<EOD
ARQUIDIOCESIS DE COCHABAMBA-BOLIVIA    
EOD;
// print a block of text using Write()
$pdf->Write(0, $txt1, '', 0, 'C', true, 0, false, false, 0);

$txt2 = "PARROQUIA \"".strtoupper($this->data->parishName)."\"<br /><br />";
$pdf->writeHTMLCell(0, 0, '', '', $txt2, 0, 1, false, true, 'C', false);

$html = "
El Presbítero que suscribe: <strong>".$this->priest->charge." ".$this->priest->firstName." ".$this->priest->lastName."</strong>.
<br />
<br /><strong>CERTIFICA:</strong> Que en el Libro Nº: <strong>".$this->data->book."</strong> de Bautismos de este archivo parroquial, Página Nº: <strong>".$this->data->page."</strong> Partida Nº: <strong>".$this->data->item."</strong> se halla inscrita la siguiente partida:
<br />Al margen:
";
$pdf->writeHTMLCell(0, 0, '', '', $html, 0, 1, false, true, 'J', false);

$html1 = "<br /><strong>\"".strtoupper($this->data->firstName." ".$this->data->firstSurname." ".$this->data->secondSurname)."\"</strong>";
$pdf->writeHTMLCell(0, 0, '', '', $html1, 0, 1, false, true, 'C', false);
$html2 = "
<br />
<br />En esta Parroquia del <strong>\"".$this->data->parishName."\"</strong>, el día <strong>".$day.", ".strftime("%d de %B del %Y",strtotime($this->data->baptismDate)).".</strong>
El suscrito párroco <strong>".$baptismPriestPrint."</strong>, bautizó solemnemente a: <strong>".strtoupper($this->data->firstName)."</strong>; 
nacido(a) en: <strong>".$bornInPrint."</strong>, el <strong>".strftime("%d de %B del %Y",strtotime($this->data->birthDate))."</strong>; hijo(a) de:
<strong>".$parentPrint."</strong>. Feligreses de esta Parroquia.
<br />Fueron Padrinos: <strong>".$godfathersPrint."</strong>.
<br />Oficialia R.C.Nº: <strong>".$this->data->oficialiaRC."</strong> Libro Nº: <strong>".$this->data->bookLN."</strong> Partida Nº: <strong>".$this->data->departure."</strong>
Folio Nº: <strong>".$this->data->folioFS."</strong>.
<br />De que doy fe yo el Párroco(Fdo.) <strong>".$attestPriestPrint."</strong>.
<br /> Observaciones: <strong>".$this->data->observation."</strong>
<br />    
<br /><strong>Los datos que se anteceden concuerdan con el original de referencia al que me remito en caso necesario.</strong>
<br />
";
$pdf->writeHTMLCell(0, 0, '', '', $html2, 0, 1, false, true, 'J', false);
$html3 = "<br />Cochabamba, ".strftime("%d de %B del %Y")."
<br />
<br />
<br />
<br />
<br />................................................
<br />".$this->priest->charge." ".$this->priest->firstName." ".$this->priest->lastName."
<br /> PÁRROCO
<br />
";
$pdf->writeHTMLCell(0, 0, '', '', $html3, 0, 1, false, true, 'C', false);


// create content for signature (image and/or text)
//$pdf->Image('C:/xampp/htdocs/SISTEMA_SISSR/vendor/tecnick.com/tcpdf/examples/images/tcpdf_signature.png', 180, 255, 15, 15, 'PNG');
//if($this->data->idUserCertificate != '0'){
$pdf->Image($this->url.'/img/tcpdf_signature.png', 180, 250, 15, 15, 'PNG');
// define active area for signature appearance
$pdf->setSignatureAppearance(180, 250, 15, 15);
// *** set an empty signature appearance ***
$pdf->addEmptySignatureAppearance(180, 250, 15, 15);
//}
// ---------------------------------------------------------

//Close and output PDF document
$pdf->Output('bautismo.pdf', 'I');

//============================================================+
// END OF FILE
//============================================================+

}else{
    echo "Documento no se puede generar comuniquese con el Administrador.";    
}