<?php
$form = $this->form;
$form->prepare();
$form->setAttributes(array(
    'action' => $this->url.'/application/dashboard/chartsthree',
    'method' => 'post',
    'name'   => 'myForm',
    'class'   => 'form-horizontal',
    'id'  => 'defaultForm'
));
?>
<div class="row">
    <div class="text-center">
        <h2 style="color:#178acc">GR&Aacute;FICA DE REPORTES</h2>
    </div>
    <!-- /.col-lg-12 -->
</div>
<!-- /.row -->
<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading" style="color:#178acc">
                <i class="fa fa-bar-chart-o fa-fw"></i> Gr&aacute;fica de l&iacute;neas
                <?php echo $this->form()->openTag($form)?>
                <div class="form-group">
                    <label class="col-md-1 control-label">Vicaría</label>
                    <div class="col-md-4">
                      <?php $idVicarious = $form->get('idVicarious');
                          echo $this->formSelect($idVicarious);
                          echo $this->formElementErrors($idVicarious);
                      ?>
                    </div>
                    <label  class="col-md-1 control-label">Sacramento</label>
                    <div class="col-md-4">
                      <?php $sacrament = $form->get('sacrament');
                          echo $this->formSelect($sacrament);
                          echo $this->formElementErrors($sacrament);
                      ?>
                    </div>
                </div>    
                <div class="form-group">    
                    <label class="col-md-1 control-label">Gestión</label>
                    <div class="col-md-2">
                      <?php $year = $form->get('year');
                          echo $this->formSelect($year);
                          echo $this->formElementErrors($year);
                       ?>
                    </div>
                </div>
                <div class="form-group">    
                    <label class="col-md-1 control-label"></label>
                    <?php echo $this->formElement($form->get('send')) ?>
                    <?php echo $this->form()->closeTag() ?>
                </div> 
                
                
            </div>
            <div class="panel-body">
                <div class="flot-chart">
                    <div class="flot-chart-content" id="flot-pie-chart"></div>

                </div>
            </div>
            <!-- /.panel-body -->
        </div>            
    </div>
    <!-- /.col-lg-8 -->        
</div>
<!-- /.row -->


  

<script type="text/javascript">
//Flot Pie Chart
$(function() {
    
    var data = [
        { data: 0.000001, label: '' },
        <?php foreach($this->data as $data_item){ ?>
             { data: <?php echo $data_item['sacrament'];?>, label: '<?php echo $data_item['parishName'];?>' },
        <?php }?>
    ];

    var plotObj = $.plot($("#flot-pie-chart"), data, {
        series: {
            pie: {
                show: true
            }
        },
        grid: {
            hoverable: true
        },
        tooltip: true,
        tooltipOpts: {
//            content: "%Y.0, %s", // show percentages, rounding to 2 decimal places,  0% percentages
            content: function(label,x,y,p){
                        return "%p.0% ("+y+"), "+label;
                    },
            shifts: {
                x: 20,
                y: 0
            },
            defaultTheme: false
        }
    });

});

</script>