<?php
$form = $this->form;
$form->prepare();
$form->setAttributes(array(
    'action' => $this->url.'/application/dashboard/chartsthree',
    'method' => 'post',
    'name'   => 'myForm',
    'id'  => 'defaultForm'
));
?>
<div class="row">
    <div class="text-center">
        <h2 style="color:#178acc">GR&Aacute;FICA DE REPORTES</h2>
    </div>
    <!-- /.col-lg-12 -->
</div>
<!-- /.row -->
<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading" style="color:#178acc">
                <i class="fa fa-bar-chart-o fa-fw"></i> Gr&aacute;fica de l&iacute;neas
                <?php echo $this->form()->openTag($form)?>
                <div class="form-group">
                    <!--<label>* Parroquia:</label>-->
                    <?php $idVicarious = $form->get('idVicarious');
                          echo $this->formSelect($idVicarious);
                          echo $this->formElementErrors($idVicarious);
                    ?>
                </div>
                <div class="form-group">
                    <!--<label>* Parroquia:</label>-->
                    <?php $year = $form->get('year');
                          echo $this->formSelect($year);
                          echo $this->formElementErrors($year);
                    ?>
                </div>
                <?php echo $this->formElement($form->get('send')) ?>
                <?php echo $this->form()->closeTag() ?>
                
            </div>
            <div class="panel-body">
                <div class="flot-chart">
                    <div class="flot-chart-content" id="flot-pie-chart"></div>

                </div>
                <p><center>Bautismos</center><p>
            </div>
            <div class="panel-body">
                <div class="flot-chart">
                    <div class="flot-chart-content" id="flot-pie-chart-two"></div>
                </div>
                <p><center>Confirmaciones</center><p>
            </div>
            <div class="panel-body">
                <div class="flot-chart">
                    <div class="flot-chart-content" id="flot-pie-chart-three"></div>
                </div>
                <p><center>Matrimonios</center><p>
            </div>
            <!-- /.panel-heading -->
<!--            <div class="panel-body">
                   <div id="morris-line-chart"></div>
            </div>-->
<!--            <div class="panel-body">
                <div class="row">
                    <div class="col-md-4">
                        <div class="panel-body">
                            <div class="flot-chart">
                                <div class="flot-chart-content" id="flot-pie-chart"></div>
                                
                            </div>
                            <p><center>Bautismos</center><p>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="panel-body">
                            <div class="flot-chart">
                                <div class="flot-chart-content" id="flot-pie-chart-two"></div>
                            </div>
                            <p><center>Confirmaciones</center><p>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="panel-body">
                            <div class="flot-chart">
                                <div class="flot-chart-content" id="flot-pie-chart-three"></div>
                            </div>
                            <p><center>Matrimonios</center><p>
                        </div>
                    </div>
                </div>
            </div>-->
            <!-- /.panel-body -->
        </div>            
    </div>
    <!-- /.col-lg-8 -->        
</div>
<!-- /.row -->
<?php 
//$value1 = "0";
//$value2 = "0";
//$value3 = "0";
//$value4 = "0";
//$value5 = "0";
//$value6 = "0";
//$value7 = "0";
//$value8 = "0";
//$value9 = "0";
//$value10 = "0";
//$value11 = "0";
//$value12 = "0";

//$valueM1 = "0";
//$valueM2 = "0";
//$valueM3 = "0";
//$valueM4 = "0";
//$valueM5 = "0";
//$valueM6 = "0";
//$valueM7 = "0";
//$valueM8 = "0";
//$valueM9 = "0";
//$valueM10 = "0";
//$valueM11 = "0";
//$valueM12 = "0";
//echo $this->year;

//foreach($this->data as $data_item){ 
////    echo $data_item['bap']." ";
////    echo $data_item['month']." ";
//    if($data_item['month'] == 1)
//        $value1 = $data_item['bap'];
//    if($data_item['month'] == 2)
//        $value2 = $data_item['bap'];
//    if($data_item['month'] == 3)
//        $value3 = $data_item['bap'];
//    if($data_item['month'] == 4)
//        $value4 = $data_item['bap'];
//    if($data_item['month'] == 5)
//        $value5 = $data_item['bap'];
//    if($data_item['month'] == 6)
//        $value6 = $data_item['bap'];
//    if($data_item['month'] == 7)
//        $value7 = $data_item['bap'];
//    if($data_item['month'] == 8)
//        $value8 = $data_item['bap'];
//    if($data_item['month'] == 9)
//        $value9 = $data_item['bap'];
//    if($data_item['month'] == 10)
//        $value10 = $data_item['bap'];
//    if($data_item['month'] == 11)
//        $value11 = $data_item['bap'];
//    if($data_item['month'] == 12)
//        $value12 = $data_item['bap'];
//}

//foreach($this->data1 as $data_item){ 
//    echo $data_item['marri']." ";
//    echo $data_item['monthM']." ";
//    if($data_item['monthM'] == 1)
//        $valueM1 = $data_item['marri'];
//    if($data_item['monthM'] == 2)
//        $valueM2 = $data_item['marri'];
//    if($data_item['monthM'] == 3)
//        $valueM3 = $data_item['marri'];
//    if($data_item['monthM'] == 4)
//        $valueM4 = $data_item['marri'];
//    if($data_item['monthM'] == 5)
//        $valueM5 = $data_item['marri'];
//    if($data_item['monthM'] == 6)
//        $valueM6 = $data_item['marri'];
//    if($data_item['monthM'] == 7)
//        $valueM7 = $data_item['marri'];
//    if($data_item['monthM'] == 8)
//        $valueM8 = $data_item['marri'];
//    if($data_item['monthM'] == 9)
//        $valueM9 = $data_item['marri'];
//    if($data_item['monthM'] == 10)
//        $valueM10 = $data_item['marri'];
//    if($data_item['monthM'] == 11)
//        $valueM11 = $data_item['marri'];
//    if($data_item['monthM'] == 12)
//        $valueM12 = $data_item['marri'];
//}
?> 

  

<script type="text/javascript">

//Flot Pie Chart
$(function() {
    
    var data = [
        <?php foreach($this->data as $data_item){ ?>
             { label: '<?php echo $data_item['parishName'];?>', data: <?php echo $data_item['bap'];?> },
        <?php }?>
    ];
//    var data = [{
//        label: "Series 0",
//        data: 0
//    }, {
//        label: "Series 1",
//        data: 30
//    }, {
//        label: "Series 2",
//        data: 90
//    }, {
//        label: "Series 3",
//        data: 40
//    }];

    var plotObj = $.plot($("#flot-pie-chart"), data, {
        series: {
            pie: {
                show: true
            }
        },
        grid: {
            hoverable: true
        },
        tooltip: true,
        tooltipOpts: {
            content: "%p.0%, %s", // show percentages, rounding to 2 decimal places
            shifts: {
                x: 20,
                y: 0
            },
            defaultTheme: false
        }
    });

});

//Flot Pie Chart Two
$(function() {

    var data = [
        <?php foreach($this->data2 as $data_item){ ?>
             { label: '<?php echo $data_item['parishName'];?>', data: <?php echo $data_item['confir'];?> },
        <?php }?>
    ];

//    var data = [{
//        label: "Series 0",
//        data: 8
//    }, {
//        label: "Series 1",
//        data: 3
//    }, {
//        label: "Series 2",
//        data: 9
//    }, {
//        label: "Series 3",
//        data: 10
//    }];

    var plotObj = $.plot($("#flot-pie-chart-two"), data, {
        series: {
            pie: {
                show: true
            }
        },
        grid: {
            hoverable: true
        },
        tooltip: true,
        tooltipOpts: {
            content: "%p.0%, %s", // show percentages, rounding to 2 decimal places
            shifts: {
                x: 20,
                y: 0
            },
            defaultTheme: false
        }
    });

});

//Flot Pie Chart Three
$(function() {

    var data = [
        <?php foreach($this->data1 as $data_item){ ?>
             { label: '<?php echo $data_item['parishName'];?>', data: <?php echo $data_item['marri'];?> },
        <?php }?>
    ];

//    var data = [{
//        label: "Series 0",
//        data: 4
//    }, {
//        label: "Series 1",
//        data: 9
//    }, {
//        label: "Series 2",
//        data: 5
//    }, {
//        label: "Series 3",
//        data: 10
//    }];

    var plotObj = $.plot($("#flot-pie-chart-three"), data, {
        series: {
            pie: {
                show: true
            }
        },
        grid: {
            hoverable: true
        },
        tooltip: true,
        tooltipOpts: {
            content: "%p.0%, %s", // show percentages, rounding to 2 decimal places
            shifts: {
                x: 20,
                y: 0
            },
            defaultTheme: false
        }
    });

});


</script>