<div class="row">
    <div class="text-center">
        <h2 style="color:#178acc">ARZOBISPADO DE COCHABAMBA</h2>
    </div>
    <!-- /.col-lg-12 -->
</div>
<!-- /.row -->
<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading" style="color:#178acc">
                Bienvenido
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                <div class="row">
                    <div class="col-md-4">
                        <center><img src="<?php echo $this->basePath() ?>/img/images/escudomons.png" alt="..." class="img-rounded" width="300" height="350"/></center>
                    </div>
                    <!-- /.col-lg-6 (nested) -->
                    <div class="col-md-8">
                        <h2 class="text-center" style="color:#178acc">Bienvenido al sistemas AC</h2>
                        <p>El sistema AC (Arzobispado de Cochabamba) es un sistema Web Administrativo para la gestión y adminsitración de los libros sacramentales.</p>
                        <p>EL sistema pretende responder a una de las necesidades más centrales del Arzobispado de Cochabamba es la de fortalecer la gestión de los libros parroquiales.</p>
                        <p>El sistema almacena toda la información de los sacramentos de bautismos, confirmaciones y matrimonios generada en las parroquias pertenecientes 
                           en el Arzobispado de Cochabamba para generar reportes estadisticos y certificados religiosos para ser entregados a las personas.</p>
                    </div>
                    <?php echo $this->form()->closeTag() ?>
                </div>
                <!-- /.row (nested) -->
            </div>
            <!-- /.panel-body -->
        </div>            
    </div>
    <!-- /.col-lg-8 -->        
</div>
