<?php
$form = $this->form;
$form->prepare();
$form->setAttributes(array(
    'action' => $this->url.'/application/dashboard/normal',
    'method' => 'post',
    'name'   => 'myForm',
    'id'  => 'defaultForm',
    'class' => 'form-horizontal'
));
?>
<div class="row">
    <div class="text-center">
        <h2 style="color:#178acc">GR&Aacute;FICA DE REPORTES</h2>
    </div>
    <!-- /.col-lg-12 -->
</div>
<!-- /.row -->
<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading" style="color:#178acc">
                <i class="fa fa-bar-chart-o fa-fw"></i> Gr&aacute;fica de l&iacute;neas
                <?php echo $this->form()->openTag($form)?>
                <div class="form-group">
                    <label class="col-md-2 control-label">Sacramento</label>
                    <div class="col-md-3">
                      <?php $sacrament = $form->get('sacrament');
                          echo $this->formSelect($sacrament);
                          echo $this->formElementErrors($sacrament);
                      ?>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-2 control-label">Vicaría</label>
                    <div class="col-md-4">
                      <?php $idVicarious = $form->get('idVicarious');
                          echo $this->formSelect($idVicarious);
                          echo $this->formElementErrors($idVicarious);
                      ?>
                    </div>
                    <label class="col-md-2 control-label">Parroquia</label>
                    <div class="col-md-4">
                      <?php $idParishes = $form->get('idParishes');
                          echo $this->formSelect($idParishes);
                          echo $this->formElementErrors($idParishes);
                      ?>
                    </div>
                </div>
                <div class="form-group">    
                    <label class="col-md-2 control-label">Desde</label>
                    <div class="col-md-2">
                        <?php
                        $startDate = $form->get('startDate');
                        echo $this->formInput($startDate);
                        echo $this->formElementErrors($startDate);
                        ?>
                    </div>
                    <label class="col-md-1 control-label">Hasta</label>
                    <div class="col-md-2">
                        <?php
                        $endDate = $form->get('endDate');
                        echo $this->formInput($endDate);
                        echo $this->formElementErrors($endDate);
                        ?>
                    </div>
            </div>
                <div class="form-group"> 
                <label class="col-md-2 control-label"></label>    
                <?php echo $this->formElement($form->get('send')) ?>
                <?php echo $this->form()->closeTag() ?>                
            </div>
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                <p style="color:#178acc"><strong>Resultado reportes</strong></p>
                <div class="table-responsive">                    
                    <table class="table table-striped table-bordered table-hover">                        
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>Sacramento</th>
                                <?php if($this->vicarious == 'TODOS') {?>
                                <th>Vicarias</th>
                                <?php }else {?>
                                <th>Parroquia</th>
                                <?php } ?>
                                <th>Total</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php $count = 1; 
                            foreach($this->data as $data_item){  ?>                           
                            <tr class="gradeC"> 
                                <td><?php echo  $count++ ?></td>
                                <td><?php echo  $this->sacrament?></td>
                                <?php if($this->vicarious == 'TODOS') {?>
                                <td><?php echo  $data_item['vicariousName']?></td>
                                <?php } else {?>
                                <td><?php echo  $data_item['parishName']?></td>
                                <?php } ?>
                                <td><?php echo  $data_item['bap']." Partidas"?></td>
                            </tr>
                            <?php } ?>
                        </tbody>
                    </table>
                </div>
            </div>
            <!-- /.panel-body -->                    
    </div>
    <!-- /.col-lg-8 -->        
</div>
<!-- /.row -->

       
 
<script type="text/javascript">

$(document).ready(function () {
    $("#inputStartDate").keydown(function (e) {
        if (e.which == 9) {
            return true;
        }
        return false;
    });
});

$(document).ready(function() {
    var nowTemp = new Date();
    var now = new Date(nowTemp.getFullYear(), nowTemp.getMonth(), nowTemp.getDate(), 0, 0, 0, 0);

    $('#inputStartDate').datepicker({
      onRender: function(date) {
        return date.valueOf() > now.valueOf() ? 'disabled' : '';
      }
    });
});

$(document).ready(function () {
    $("#inputEndDate").keydown(function (e) {
        if (e.which == 9) {
            return true;
        }
        return false;
    });
});

$(document).ready(function() {
    var nowTemp = new Date();
    var now = new Date(nowTemp.getFullYear(), nowTemp.getMonth(), nowTemp.getDate(), 0, 0, 0, 0);

    $('#inputEndDate').datepicker({
      onRender: function(date) {
        return date.valueOf() > now.valueOf() ? 'disabled' : '';
      }
    });
});

$(document).ready(function() {
$('#inputSelectIdVicarious').change(function(){
    var idVicarious = $(this).val();
    $.ajax({
        type: "POST",
        url: "<?php echo $this->url.'/application/dashboard/getParishesByVicarious'; ?>",
        data: "idVicarious="+idVicarious,
        success: function(msg){ 
            console.debug(msg);
            $("#inputSelectIdParish").html(msg);
        }
    });
});
});

//$(document).ready(function () {
//    $("#inputSelectType").change(function () {
//        var value = $(this).val();
//        if(value == 'Reportes por torta'){
//            $("#inputStartDate").show();
//        }else{
//            $("#inputStartDate").hide();
//        }    
//    });
//});
        

</script>