<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Arquidiocesis\Module'                        => __DIR__ . '/Module.php',
    'Arquidiocesis\Controller\VicariasController' => __DIR__ . '/src/Arquidiocesis/Controller/VicariasController.php',
    'Arquidiocesis\Framework\TestCase'        => __DIR__ . '/tests/Arquidiocesis/Framework/TestCase.php',
    'Arquidiocesis\SampleTest'                => __DIR__ . '/tests/Arquidiocesis/SampleTest.php',
);