<?php
$form = $this->form;
$form->prepare();
$form->setAttributes(array(
    'action' => $this->url.'/archdiocese/vicarious/edit/'.$this->id,
    'method' => 'post',
    'name'   => 'myForm',
    'id'  => 'defaultForm'
));
?>
<div class="row">
    <div class="text-center">
        <h2 style="color:#178acc"><?php echo $this->title ?></h2>    
    </div>
</div>
<!-- /.row -->
<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading" style="color:#178acc">
                Registro de editar vicar&iacute;a
            </div>
            <div class="panel-body">
                <div class="row">
                    <?php echo $this->form()->openTag($form)?>
                    <div class="col-md-6">
                        <h3 style="color:#178acc">Informaci&oacute;n b&aacute;sica</h3>
                            <?php $id= $form->get('id');
                                echo $this->formInput($id);
                            ?>
                            <div class="form-group">
                                <label>* Vicar&iacute;a:</label>
                                <?php $vicariousName= $form->get('vicariousName');
                                    echo $this->formInput($vicariousName);
                                    echo $this->formElementErrors($vicariousName);
                                ?>
                            </div>
                            <div class="form-group">
                                <label>Ubicaci&oacute;n:</label>
                                <?php $location= $form->get('location');
                                    echo $this->formInput($location);
                                    echo $this->formElementErrors($location);
                                ?>
                            </div> 
                        <?php echo $this->formElement($form->get('modify')) ?>
                        <a href="<?php echo $this->basePath() ?>/archdiocese/vicarious/index" class="btn btn-default" role="button">Cancelar</a>
                    </div>
                    <!-- /.col-lg-6 (nested) -->                    
                    <?php echo $this->form()->closeTag() ?>
                </div>
                <!-- /.row (nested) -->
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-12 -->
</div>
<!-- /.row -->
<script type="text/javascript">
$(document).ready(function() {
    $('#defaultForm').bootstrapValidator({
//        live: 'disabled',
        message: 'This value is not valid',
        feedbackIcons: {
            valid: 'glyphicon glyphicon-ok',
            invalid: 'glyphicon glyphicon-remove',
            validating: 'glyphicon glyphicon-refresh'
        },
        fields: {
            vicariousName: {
                validators: {
                    notEmpty: {
                        message: 'El campo vicaría es obligatorio.'
                    },
                    stringLength: {
                        min: 3,
                        max: 50,
                        message: 'El campo vicaría debe ser una cadena de texto mayor a 3 caracteres.'
                    }
                }
            },
        }
    });

    // Validate the form manually
    $('#validateBtn').click(function() {
        $('#defaultForm').bootstrapValidator('validate');
    });

    $('#resetBtn').click(function() {
        $('#defaultForm').data('bootstrapValidator').resetForm(true);
    });
});
</script>