<?php
$form = $this->form;
$form->prepare();
$form->setAttributes(array(
    'action' => $this->url,
    'method' => 'post',
    'name'   => 'myForm',
    'id'  => 'defaultForm'
));
?>

</br>
</br>
<p class="text-center"><img src="<?php echo $this->basePath() ?>/img/img2.png" width="150" height="75"></p>
<div class="row">    
    <div class="col-md-4 col-md-offset-4">    
        <div class="login-panel panel panel-default">
            <div class="panel-heading" style="color:#178acc">
                <h3 class="panel-title"><center><?php echo $this->title ?></center></h3>
            </div>
            <div class="panel-body">
                <?php echo $this->form()->openTag($form)?>
                    <fieldset>
                        <div class="form-group input-group">
                            <span class="input-group-addon"><span class="glyphicon glyphicon-user"></span></span>
                            <?php $email= $form->get('email');
                                echo $this->formInput($email);
                            ?>
                        </div>
                        <div class="form-group input-group" style="font-size: 12px">
                            <?php 
                             echo $this->messages;
                            ?> 
                        </div>                        
                        <!-- Change this to a button or input when using this as a form -->
                        <?php echo $this->formElement($form->get('send')) ?> 
                        
                    </fieldset>
                <?php echo $this->form()->closeTag() ?>
            </div>
        </div>        
    </div>
</div>
