</br>
</br>
<p class="text-center"><img src="<?php echo $this->basePath() ?>/img/img2.png" width="150" height="75"></p>
<div class="row">    
    <div class="col-md-4 col-md-offset-4">    
        <div class="login-panel panel panel-default">
            <div class="panel-heading" style="color:#178acc">
                <h3 class="panel-title"><center><?php echo $this->title; ?></center></h3>
            </div>
            <div class="panel-body">
                    <fieldset>                        
                        <div class="form-group input-group" style="font-size: 12px">
                            <p>Hemos enviado una nueva contraseña a tu dirección de correo electrónico.</p>
                            <br />
                            <p>Una vez recibida la contraseña puede utilizar la 
                                <a href="<?php echo $this->basePath() ?>/" style="color:#178acc">p&aacute;gina de acceso</a> para iniciar sesi&oacute;n.</p>
                        </div>
                    </fieldset>
            </div>
        </div>        
    </div>
</div>
