<?php
$form = $this->form;
$form->prepare();
$form->setAttributes(array(
    'action' => $this->url.'/archdiocese/parishes/edit/'.$this->id,
    'method' => 'post',
    'name'   => 'myForm',
    'id'  => 'defaultForm'
));
?>
<div class="row">
    <div class="text-center">
        <h2 style="color:#178acc"><?php echo $this->title ?></h2>    
    </div>
</div>
<!-- /.row -->
<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading" style="color:#178acc">
                Editar Parroquia
            </div>
            <div class="panel-body">
                <div class="row">
                    <?php echo $this->form()->openTag($form)?>
                    <div class="col-md-6">
                        <h3>Informaci&oacute;n b&aacute;sica</h3>
                            <?php $id= $form->get('id');
                                echo $this->formInput($id);
                            ?>
                            <div class="form-group">
                                <label>* Parroquia:</label>
                                <?php $parishName= $form->get('parishName');
                                    echo $this->formInput($parishName);
                                    echo $this->formElementErrors($parishName);
                                ?>
                            </div>
                            <div class="form-group">
                                <label>Tel&eacute;fono:</label>
                                <?php $phone= $form->get('phone');
                                    echo $this->formInput($phone);
                                    echo $this->formElementErrors($phone);
                                ?> 
                            </div>                            
                            <div class="form-group">
                                <label>Direcci&oacute;n:</label>
                                <?php $address= $form->get('address');
                                    echo $this->formInput($address);
                                ?>
                            </div>
                            <div class="form-group">
                                <label>* Vicar&iacute;a a la que pertenece:</label>
                                <?php $idVicarious= $form->get('idVicarious');
                                    echo $this->formSelect($idVicarious);
                                    echo $this->formElementErrors($idVicarious);
                                ?>
                            </div>
                        <?php echo $this->formElement($form->get('modify')) ?>
                        <a href="<?php echo $this->basePath() ?>/archdiocese/parishes/index" class="btn btn-default" role="button">Cancelar</a>
                    </div>
                    <!-- /.col-lg-6 (nested) -->                    
                    <?php echo $this->form()->closeTag() ?>
                </div>
                <!-- /.row (nested) -->
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-12 -->
</div>
<!-- /.row -->
<script type="text/javascript">
$(document).ready(function() {
    $('#defaultForm').bootstrapValidator({
//        live: 'disabled',
        message: 'This value is not valid',
        feedbackIcons: {
            valid: 'glyphicon glyphicon-ok',
            invalid: 'glyphicon glyphicon-remove',
            validating: 'glyphicon glyphicon-refresh'
        },
        fields: {
            parishName: {
                validators: {
                    notEmpty: {
                        message: 'El campo parroquia es obligatorio.'
                    },
                    stringLength: {
                        min: 3,
                        max: 50,
                        message: 'El campo parroquia debe ser una cadena de texto mayor a 3 caracteres.'
                    }
                }
            },
            idVicarious: {
                validators: {
                    notEmpty: {
                        message: 'El campo vicaría es obligatorio.'
                    }
                }
            },
            phone: {
                validators: {                    
                    stringLength: {
                        min: 7,
                        max: 15,
                        message: 'El campo teléfono debe ser una cadena de texto mayor a 6 caracteres.'
                    },
                    regexp: {
                        regexp: /^[0-9\-]*$/,
                        message: 'El teléfono solo puede contener números enteros y [-].'
                    },
                }
            },
        }
    });

    // Validate the form manually
    $('#validateBtn').click(function() {
        $('#defaultForm').bootstrapValidator('validate');
    });

    $('#resetBtn').click(function() {
        $('#defaultForm').data('bootstrapValidator').resetForm(true);
    });
});
</script>

