<?php
$form = $this->form;
$form->prepare();
$form->setAttributes(array(
    'action' => $this->url.'/sacraments/books/editp/'.$this->id,
    'method' => 'post',
    'name'   => 'myForm',
    'id'  => 'defaultForm'
));
?>
<div class="row">
    <div class="text-center">
        <h2 style="color:#178acc"><?php echo $this->title ?></h2>    
    </div>
</div>
<!-- /.row -->
<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading" style="color:#178acc">
                Registro de editar libro
            </div>
            <div class="panel-body">
                <div class="row">
                    <?php echo $this->form()->openTag($form)?>
                    <div class="col-md-6">
                        <h3 style="color:#178acc">Informaci&oacute;n basica</h3>
                            <?php $id= $form->get('id');
                                echo $this->formInput($id);
                            ?>                            
                            <div class="form-group">
                                <label>* Sacramento:</label>
                                <?php $sacramentName= $form->get('sacramentName');
                                    echo $this->formSelect($sacramentName);
                                    echo $this->formElementErrors($sacramentName);
                                ?>
                            </div>
                            <div class="form-group">
                                <label>* Numero de libro:</label>
                                <?php $book= $form->get('book');
                                    echo $this->formInput($book);
                                    echo $this->formElementErrors($book);
                                ?> 
                            </div>                    
                        <?php echo $this->formElement($form->get('modify')) ?>
                        <a href="<?php echo $this->basePath() ?>/sacraments/books/indexp" class="btn btn-default" role="button">Cancelar</a>
                    </div>
                    <!-- /.col-lg-6 (nested) -->                    
                    <?php echo $this->form()->closeTag() ?>
                </div>
                <!-- /.row (nested) -->
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-12 -->
</div>
<!-- /.row -->
<script type="text/javascript">
$(document).ready(function() {
    $('#defaultForm').bootstrapValidator({
//        live: 'disabled',
        message: 'This value is not valid',
        feedbackIcons: {
            valid: 'glyphicon glyphicon-ok',
            invalid: 'glyphicon glyphicon-remove',
            validating: 'glyphicon glyphicon-refresh'
        },
        fields: {
            book: {
                validators: {
                    notEmpty: {
                        message: 'El libro es requerido'
                    }
                }
            },
        }
    });

    // Validate the form manually
    $('#validateBtn').click(function() {
        $('#defaultForm').bootstrapValidator('validate');
    });

    $('#resetBtn').click(function() {
        $('#defaultForm').data('bootstrapValidator').resetForm(true);
    });
});
</script>
