<div class="row">
    <div class="text-center">
        <h2 style="color:#178acc"><?php echo $this->title ?></h2>    
    </div>
</div>
<!-- /.row -->
<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <a href="<?php echo $this->basePath() ?>/sacraments/books/index" style="color:#178acc"><span class="glyphicon glyphicon-circle-arrow-left"></span> Atr&aacute;s</a>
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body"> 
<!--                <div class="col-lg-2">
                    <img data-src="holder.js/140x140" class="img-rounded" alt="140x140" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxNDAiIGhlaWdodD0iMTQwIj48cmVjdCB3aWR0aD0iMTQwIiBoZWlnaHQ9IjE0MCIgZmlsbD0iI2VlZSI+PC9yZWN0Pjx0ZXh0IHRleHQtYW5jaG9yPSJtaWRkbGUiIHg9IjcwIiB5PSI3MCIgc3R5bGU9ImZpbGw6I2FhYTtmb250LXdlaWdodDpib2xkO2ZvbnQtc2l6ZToxMnB4O2ZvbnQtZmFtaWx5OkFyaWFsLEhlbHZldGljYSxzYW5zLXNlcmlmO2RvbWluYW50LWJhc2VsaW5lOmNlbnRyYWwiPjE0MHgxNDA8L3RleHQ+PC9zdmc+" style="width: 140px; height: 140px;">                
                </div>-->
                <div class="col-md-8">
                    <h3 style="color:#178acc">Informaci&oacute;n b&aacute;sica</h3>
                    <p>Parroquia: <strong><a href="<?php echo $this->basePath() ?>/archdiocese/parishes/view/<?php echo $this->data->idParish ?>" style="color:#178acc"><?php echo $this->data->parishName?></a></strong></p>
                    <p>Libro: <strong><?php echo "Libro de ".$this->data->sacramentName." Nº: ".$this->data->book ?></strong></p>
                    <p>C&oacute;digo del libro: <strong><?php echo $this->data->code ?></strong></p>
                    <p>Partida inicial: <strong><?php echo $this->data->startItem ?></strong></p>
                    <p>Fecha de registro: <strong><?php echo $this->data->registrationDate ?></strong></p>
                    <p>Tipo del libro: <strong><?php echo $this->data->statusBook." ".$this->data->typeBook ?></strong></p>                    
                    <a href="<?php echo $this->basePath() ?>/sacraments/books/edit/<?php echo  $this->data->id ?>" class="btn btn-primary" role="button">Editar</a> 
                    </br>                    
                </div>
            </div>            
            <!-- /.panel-body -->
            <div class="panel-body">
                <p style="color:#178acc"><strong>Partidas registradas en este libro:</strong></p>
                <div class="table-responsive">                    
                    <table class="table table-striped table-bordered table-hover">                        
                        <thead>
                            <tr>                                
                                <th>Persona</th>
                                <th>P&aacute;gina</th>
                                <th>Partida</th>
                                <th>Acciones</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php foreach($this->baptism as $data_item){ ?>                           
                            <tr class="gradeC"> 
                                <td><?php echo  $data_item->firstName." ".$data_item->firstSurname." ".$data_item->secondSurname?></td>
                                <td><?php echo  $data_item->page?></td>
                                <td><?php echo  $data_item->item?></td>
                                <td>                                
                                <a href="<?php echo $this->basePath() ?>/sacraments/baptisms/view/<?php echo  $data_item->id?>" title="Ver" style="color:#178acc"><span class="glyphicon glyphicon-eye-open"></span></a>                              
                                
                                </td>
                            </tr>
                            <?php } ?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-12 -->
</div>
