<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Usuarios\Module'                        => __DIR__ . '/Module.php',
    'Usuarios\Controller\UsuariosController' => __DIR__ . '/src/Usuarios/Controller/UsuariosController.php',
    'UsuariosTest\Framework\TestCase'        => __DIR__ . '/tests/Usuarios/Framework/TestCase.php',
    'UsuariosTest\SampleTest'                => __DIR__ . '/tests/Usuarios/SampleTest.php',
);